#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package}.ws.hello;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 *
 */
@WebServiceClient(name = "HelloService",
            targetNamespace = "http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/",
            wsdlLocation = "HelloService.wsdl")
public class HelloService extends Service {

    private final static URL HELLOSERVICE_WSDL_LOCATION;

    private final static Logger logger = LoggerFactory.getLogger(HelloService.class.getName());

    static {
        final URL url =
                    HelloService.class
                                .getResource("/fr/gouv/diplomatie/bouchonwebservice/wsdl/HelloService.wsdl");
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService(
                final URL wsdlLocation, final QName serviceName) {

        super(wsdlLocation, serviceName);
    }

    public HelloService() {

        super(HELLOSERVICE_WSDL_LOCATION, new QName(
                    "http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/", "HelloService"));
    }

    /**
     *
     * @return returns IHelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public IHelloService getHelloServicePort() {

        return super.getPort(new QName("http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/",
                    "HelloServicePort"), IHelloService.class);
    }

    /**
     *
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
     *            features not in the <code>features</code> parameter will have their default values.
     * @return returns IHelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public IHelloService getHelloServicePort(final WebServiceFeature... features) {

        return super.getPort(new QName("http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/",
                    "HelloServicePort"), IHelloService.class, features);
    }

}
